//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using Ark.ResultCheckers.Data;
using Ark.ResultCheckers.Entities;
using Ark.ResultCheckers.Dtos;
using Ark.ResultCheckers.Dtos.Caches;

namespace Ark.ResultCheckers.Data.Services
{
    public partial class SessionService : BaseService
    {
    
        public SessionService(AppDbContext context)
        : base(context)
        {
           
        }
    
        // +EntityQuery
        public static IQueryable<Session> EntityQuery(AppDbContext context, string[] includeNavigations, params Expression<Func<Session, bool>>[] filters)
        {
            var query = context.Sessions.AsQueryable();
    
            if (includeNavigations != null && includeNavigations.Count() > 0)
            {
                // include navigation entity
                foreach (var navigation in includeNavigations)
                {
                    query = query.Include(navigation);
                }
            }
    
            if (filters != null && filters.Count() > 0)
            {
                // filter entity
                foreach (var filter in filters)
                {
                    query = query.Where(filter);
                }
            }
    
            return query;
        }
    
        protected IQueryable<SessionDto> SessionQuery(String[] includeNavigations, params Expression<Func<Session, bool>>[] filters)
        {
            var query = EntityQuery(_context, includeNavigations, filters);
    
            return query.Select(SessionDto.AsSessionDto);
        }        
    
        public async Task<List<SessionDto>> GetSessionsAsync(String[] includeNavigations, params Expression<Func<Session, bool>>[] filters)
        {
            IQueryable<SessionDto> query = SessionQuery(includeNavigations, filters);
    
            return await query
                        // Use AsNoTracking to disable EF change tracking
                        // Use ToListAsync to avoid blocking a thread
                        .AsNoTracking().ToListAsync();
        }
    
        public async Task<SessionDto> GetSessionAsync(String[] includeNavigations, params Expression<Func<Session, bool>>[] filters)
        {
            // Get Session  
            IQueryable<SessionDto> query = SessionQuery(includeNavigations, filters);
    
            return await query
                    // Use AsNoTracking to disable EF change tracking
                    // Use ToListAsync to avoid blocking a thread
                    .AsNoTracking().FirstOrDefaultAsync();
        }
    
        public async Task<SessionDto> GetSessionAsync(int id, String[] includeNavigations, params Expression<Func<Session, bool>>[] filters)
        {
            // Get Session  
            IQueryable<SessionDto> query = SessionQuery(includeNavigations, filters);
    
            return await query
                    // Use AsNoTracking to disable EF change tracking
                    // Use ToListAsync to avoid blocking a thread
                    .AsNoTracking().SingleOrDefaultAsync(m => m.Id == id);
        }
        // -EntityQuery
    
        // +DtoQuery
        public static IQueryable<SessionDto> DtoQuery(AppDbContext context, string[] includeNavigations, params Expression<Func<SessionDto, bool>>[] filters)
        {
            var query = context.Sessions.AsQueryable();
    
            if (includeNavigations != null && includeNavigations.Count() > 0)
            {
                // include navigation entity
                foreach (var navigation in includeNavigations)
                {
                    query = query.Include(navigation);
                }
            }
    
            var query2 = query.Select(SessionDto.AsSessionDto);
    
            if (filters != null && filters.Count() > 0)
            {
                // filter entity
                foreach (var filter in filters)
                {
                    query2 = query2.Where(filter);
                }
            }
    
            return query2;
        }
    
        protected IQueryable<SessionDto> SessionDtoQuery(String[] includeNavigations, params Expression<Func<SessionDto, bool>>[] filters)
        {
            var query = DtoQuery(_context, includeNavigations, filters);
    
            return query;
        }        
    
        public async Task<List<SessionDto>> GetSessionDtoesAsync(String[] includeNavigations, params Expression<Func<SessionDto, bool>>[] filters)
        {
    
            IQueryable<SessionDto> query = SessionDtoQuery(includeNavigations, filters);
    
            return await query
                        // Use AsNoTracking to disable EF change tracking
                        // Use ToListAsync to avoid blocking a thread
                        .AsNoTracking().ToListAsync();
        }
    
        public async Task<SessionDto> GetSessionDtoAsync(String[] includeNavigations, params Expression<Func<SessionDto, bool>>[] filters)
        {
            // Get Session  
            IQueryable<SessionDto> query = SessionDtoQuery(includeNavigations, filters);
    
            return await query
                    // Use AsNoTracking to disable EF change tracking
                    // Use ToListAsync to avoid blocking a thread
                    .AsNoTracking().FirstOrDefaultAsync();
        }
    
        public async Task<SessionDto> GetSessionDtoAsync(int id, String[] includeNavigations, params Expression<Func<SessionDto, bool>>[] filters)
        {
            // Get Session  
            IQueryable<SessionDto> query = SessionDtoQuery(includeNavigations, filters);
    
            return await query
                    // Use AsNoTracking to disable EF change tracking
                    // Use ToListAsync to avoid blocking a thread
                    .AsNoTracking().SingleOrDefaultAsync(m => m.Id == id);
        }
        // -DtoQuery
    
        public async Task<SessionDto> CreateSessionAsync(SessionDto sessionDto, string username)
        {
    
            if (_context.Sessions.Any(a => a.Name == sessionDto.Name) == true)
            {
                throw new Exception("Record exist and caused a conflict!");
            }
    
            OnCreate(sessionDto, username);
    
            var entity = SessionDto.AsSessionFunc(sessionDto);
            
            ToEntity(ref entity, sessionDto);
            //entity.InsertUser = entity.LastActivityUser = username;
            //entity.InsertDateTime = entity.LastActivityDateTime = DateTime.UtcNow;
            entity.AddTracker(username);
    
            _context.Sessions.Add(entity);
    
            OnBeforeCreate(entity, username);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch(Exception ex)
            {
                // _context.Entry(entity).State = EntityState.Detached;
                throw new Exception("Add error", ex);
            }
            finally
            {
                // _context.Entry(entity).State = EntityState.Detached;
            }
            OnAfterCreate(entity, username);
    
            // sessionDto = SessionDto.AsSessionDtoFunc(entity);
            sessionDto = await GetSessionDtoAsync(entity.Id, SessionDto.IncludeNavigations());
        
            return sessionDto;
        }
        partial void OnCreate(SessionDto sessionDto, string username);
        partial void OnBeforeCreate(Session entity, string username);
        partial void OnAfterCreate(Session entity, string username);
    
        public async Task<bool> UpdateSessionAsync(SessionDto sessionDto, string username/*, String[] includeNavigations, params Expression<Func<Session, bool>>[] filters*/)
        {
            OnUpdate(sessionDto, username);
            
            // Get Session  
            var entity = EntityQuery(_context, SessionDto.IncludeNavigations())
                                    .FirstOrDefault(x => x.Id == sessionDto.Id);
    
            if (entity != null)
            {
                entity = SessionDto.ToSessionFunc(entity, sessionDto);
    
                ToEntity(ref entity, sessionDto);
                //entity.UpdateUser = entity.LastActivityUser = username;
                //entity.UpdateDateTime = entity.LastActivityDateTime = DateTime.UtcNow;
                entity.EditTracker(username);
    
                OnBeforeUpdate(entity, username);
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch(Exception ex)
                {
                    // _context.Entry(entity).State = EntityState.Detached;
                    throw new Exception("Update error", ex);
                }
                finally
                {
                    // _context.Entry(entity).State = EntityState.Detached;
                }
                OnAfterUpdate(entity, username);        
            }
            else
            {
                return false;
            }
    
            return true;
        }
        partial void OnUpdate(SessionDto sessionDto, string username);
        partial void OnBeforeUpdate(Session entity, string username);
        partial void OnAfterUpdate(Session entity, string username);
    
        public async Task<bool> DeleteSessionAsync(SessionDto sessionDto)
        {
            OnDelete(sessionDto);
    
            var entity = _context.Sessions
                                .Where(x => x.Id == sessionDto.Id)
                                .FirstOrDefault();
    
            if (entity != null)
            {
                _context.Sessions.Remove(entity);
    
                OnBeforeDelete(entity);
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateException ex)
                {
                    // _context.Entry(entity).State = EntityState.Detached;
    
                    var sqlException = ex.GetBaseException() as SqlException;
    
                    if (sqlException != null)
                    {
                        var errorMessage = "deleting error";
    
                        var number = sqlException.Number;
        
                        if (number == 547)
                        {
                            string table = GetErrorTable(sqlException) ?? "descendant";
                            errorMessage = $"Must delete {table} records before deleting Session";
                        }
    
                        throw new Exception(errorMessage, ex);
                    }
                }
                finally
                {
                    // _context.Entry(entity).State = EntityState.Detached;
                }
                OnAfterDelete(entity);    
            }
            else
            {
                return false;
            }
    
            return true;
        }
        partial void OnDelete(SessionDto sessionDto);
        partial void OnBeforeDelete(Session entity);
        partial void OnAfterDelete(Session entity);
    
        public async Task<List<SessionCache>> GetSessionCachesAsync()
        {
            var list = await _context.Sessions.Select(SessionCache.AsSessionCache)
                        
                        // Use AsNoTracking to disable EF change tracking
                        // Use ToListAsync to avoid blocking a thread
                        .AsNoTracking().ToListAsync();
            return list.OrderBy(o => o.Name).ToList();
        }
    
        partial void ToEntity(ref Session entity, SessionDto sessionDto);    
    }
}
