//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.Iskools.Entities
{
    
    using System;
        
    public partial class AppSetting
    {
        public String AppSettingName { get; }
    }
    
    public partial class Staff
    {
        public String StaffName { get; }
    }
    
    public partial class Student
    {
        public String StudentName { get; }
    }
    
    public partial class StudentPdfForm
    {
        public String StudentPdfFormName { get; }
    }
    
    public partial class SubjectContent
    {
        public String SubjectContentName { get; }
    }
    
    public partial class SubjectStaff
    {
        public String SubjectStaffName { get; }
    }
    
    public partial class SubjectStudent
    {
        public String SubjectStudentName { get; }
    }
    
}
