//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.Iskools.Api2.Controllers
{
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Caching.Memory;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Threading.Tasks;
    using Ark.Iskools.Dtos.Caches;
    
    public partial class ApiController : ControllerBase
    {
    
        protected static ConcurrentDictionary<string, DateTime> _cacheItems = new ConcurrentDictionary<string, DateTime>();
    
    	#region Cache
    
    	protected void RemoveCache(string key)
        {
    		_cache.Remove(key);
        }
    
    	
    	protected List<AppSettingCache> CacheAppSettings()
        {
            //get
            {
                List<AppSettingCache> list;
    
                if (!_cache.TryGetValue(CacheKeys.AppSetting, out list))
                {
    
                    var query = _context.AppSettings.Where(w => w.IsVisible).Select(AppSettingCache.AsAppSettingCache);
                    OnCacheQuery(ref query);
                    list = query.ToList();
                    // Set cache options.
                    var cacheOptions = new MemoryCacheEntryOptions().SetSlidingExpiration(TimeSpan.FromSeconds(600));
    
                    _cache.Set(CacheKeys.AppSetting, list, cacheOptions);
                    _cacheItems.TryAdd(CacheKeys.AppSetting, DateTime.UtcNow);
                }
                return list;
            }
        }
    	partial void OnCacheQuery(ref IQueryable<AppSettingCache> query);
        #endregion
    
    	
    }
}
