//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.Iskools.Api2.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Caching.Memory;
    using Ark.Iskools.Dtos.Caches;
    using Ark.Iskools.Data;
    
    [Route("api2/[controller]")]    
    [ApiController]
    // [Authorize]
    [AllowAnonymous]
    
    public partial class CachesController : ApiController
    {
        public CachesController(AppDbContext context, IWebHostEnvironment env, IMemoryCache memoryCache) : base(context, env, memoryCache)
        {
        }
    	
        [HttpGet("AppSettings")]
        public IEnumerable<AppSettingCache> GetAppSettings()
        {
            return this.CacheAppSettings();
        }
    
    
    	
    }
}
