//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.ResultCheckers.Entities
{

    using System;

    public partial class AppSetting
    {
        partial void OnAppSettingDescription()
        {
            _appSettingDescription = $"{Key}-{Value}";
        }
    }
    public partial class BulkCard
    {
    }
    public partial class BulkStudentCourse
    {
    }
    public partial class Card
    {
        partial void OnCardDescription()
        {
            _cardDescription = $"{Pin}-({Owner})";
        }
    }
    public partial class Course
    {
        partial void OnCourseDescription()
        {
            _courseDescription = $"{Code}- {Title} ({Unit})";
        }
    }
    public partial class Student
    {
        partial void OnStudentDescription()
        {
            _studentDescription = $"{MatricNo}- {Firstname} {Middlename} {Lastname}";
        }
    }
    public partial class StudentCourse
    {
        partial void OnStudentCourseDescription()
        {
            _studentCourseDescription = $"Session({SessionId})-Semester({SemesterId})-Course({CourseId})-Student({StudentId})-{Score} ";
        }
    }
}
