//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code.Dtos.Caches
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq.Expressions;
    using Code.Dtos.Entities;
    
    public partial class BaseNameEntityCache : BaseEntityCache
    {
        public BaseNameEntityCache()
        {
            OnInitialize();
        }
    
        partial void OnInitialize();
    
    
        private static Expression<Func<BaseNameEntity, string>> _orderBaseNameEntity;
        public static Expression<Func<BaseNameEntity, string>> OrderBaseNameEntity
        {
            get
            {
                SetConverters();
                return _orderBaseNameEntity;
            }
        }
        
    	private static Expression<Func<BaseNameEntity, BaseNameEntityCache>> _asBaseNameEntityCache;
        public static Expression<Func<BaseNameEntity, BaseNameEntityCache>> AsBaseNameEntityCache
        {
            get
            {
                SetConverters();
                return _asBaseNameEntityCache;
            }
        }
        
        private static Func<BaseNameEntity, BaseNameEntityCache> _asBaseNameEntityCacheFunc;
        public static Func<BaseNameEntity, BaseNameEntityCache> AsBaseNameEntityCacheFunc
        {
            get
            {
                SetConverters();
                return _asBaseNameEntityCacheFunc;
            }
        }
        
    	private static void SetConverters()
        {
            _orderBaseNameEntity = x => x.Id.ToString();
    
            _asBaseNameEntityCache = x => new BaseNameEntityCache
            {
    			Id = x.Id,
                
                Name = null, //[x.Name],
    			
            };
    
            OnSetConverters();
    
            _asBaseNameEntityCacheFunc = _asBaseNameEntityCache.Compile();
        }
    
        static partial void OnSetConverters();
    
    
    	
    }
}
