//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.ResultCheckers.Dtos.Caches
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq.Expressions;
    using Ark.ResultCheckers.Entities;
    
    public partial class CardCache : BaseEntityCache
    {
        public CardCache()
        {
            OnInitialize();
        }
    
        partial void OnInitialize();
    
    
        private static Expression<Func<Card, string>> _orderCard;
        public static Expression<Func<Card, string>> OrderCard
        {
            get
            {
                SetConverters();
                return _orderCard;
            }
        }
        
    	private static Expression<Func<Card, CardCache>> _asCardCache;
        public static Expression<Func<Card, CardCache>> AsCardCache
        {
            get
            {
                SetConverters();
                return _asCardCache;
            }
        }
        
        private static Func<Card, CardCache> _asCardCacheFunc;
        public static Func<Card, CardCache> AsCardCacheFunc
        {
            get
            {
                SetConverters();
                return _asCardCacheFunc;
            }
        }
        
    	private static void SetConverters()
        {
            _orderCard = x => x.Id.ToString();
    
            _asCardCache = x => new CardCache
            {
    			Id = x.Id,
                
                Name = null, //[x.Name],
    			
            };
    
            OnSetConverters();
    
            _asCardCacheFunc = _asCardCache.Compile();
        }
    
        static partial void OnSetConverters();
    
    
    	
    }
}
