//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.ResultCheckers.Dtos.Caches
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq.Expressions;
    using Ark.ResultCheckers.Entities;
    
    public partial class SessionCache : BaseNameEntityCache
    {
        public SessionCache()
        {
            OnInitialize();
        }
    
        partial void OnInitialize();
    
    
        private static Expression<Func<Session, string>> _orderSession;
        public static Expression<Func<Session, string>> OrderSession
        {
            get
            {
                SetConverters();
                return _orderSession;
            }
        }
        
    	private static Expression<Func<Session, SessionCache>> _asSessionCache;
        public static Expression<Func<Session, SessionCache>> AsSessionCache
        {
            get
            {
                SetConverters();
                return _asSessionCache;
            }
        }
        
        private static Func<Session, SessionCache> _asSessionCacheFunc;
        public static Func<Session, SessionCache> AsSessionCacheFunc
        {
            get
            {
                SetConverters();
                return _asSessionCacheFunc;
            }
        }
        
    	private static void SetConverters()
        {
            _orderSession = x => x.Name;
    
            _asSessionCache = x => new SessionCache
            {
    			Id = x.Id,
                
                Name = x.Name,
    			
            };
    
            OnSetConverters();
    
            _asSessionCacheFunc = _asSessionCache.Compile();
        }
    
        static partial void OnSetConverters();
    
    
    	
    }
}
