//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Extensions.DependencyInjection;

public static class DataServiceExtension
{
    public static void ConfigureServices(IServiceCollection services)
    {
        services.AddTransient<AppSettingService>();
        services.AddTransient<CardService>();
        services.AddTransient<CourseService>();
        services.AddTransient<GradeService>();
        services.AddTransient<SemesterService>();
        services.AddTransient<SessionService>();
        services.AddTransient<StudentService>();
        services.AddTransient<StudentCourseService>();
    }
}
