//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using Ark.ResultCheckers.Data;
using Ark.ResultCheckers.Entities;
using Ark.ResultCheckers.Dtos;
using Ark.ResultCheckers.Dtos.Caches;

namespace Ark.ResultCheckers.Data.Services
{
    public partial class SemesterService : BaseService
    {
    
        public SemesterService(AppDbContext context)
        : base(context)
        {
           
        }
    
        // +EntityQuery
        public static IQueryable<Semester> EntityQuery(AppDbContext context, string[] includeNavigations, params Expression<Func<Semester, bool>>[] filters)
        {
            var query = context.Semesters.AsQueryable();
    
            if (includeNavigations != null && includeNavigations.Count() > 0)
            {
                // include navigation entity
                foreach (var navigation in includeNavigations)
                {
                    query = query.Include(navigation);
                }
            }
    
            if (filters != null && filters.Count() > 0)
            {
                // filter entity
                foreach (var filter in filters)
                {
                    query = query.Where(filter);
                }
            }
    
            return query;
        }
    
        protected IQueryable<SemesterDto> SemesterQuery(String[] includeNavigations, params Expression<Func<Semester, bool>>[] filters)
        {
            var query = EntityQuery(_context, includeNavigations, filters);
    
            return query.Select(SemesterDto.AsSemesterDto);
        }        
    
        public async Task<List<SemesterDto>> GetSemestersAsync(String[] includeNavigations, params Expression<Func<Semester, bool>>[] filters)
        {
            IQueryable<SemesterDto> query = SemesterQuery(includeNavigations, filters);
    
            return await query
                        // Use AsNoTracking to disable EF change tracking
                        // Use ToListAsync to avoid blocking a thread
                        .AsNoTracking().ToListAsync();
        }
    
        public async Task<SemesterDto> GetSemesterAsync(String[] includeNavigations, params Expression<Func<Semester, bool>>[] filters)
        {
            // Get Semester  
            IQueryable<SemesterDto> query = SemesterQuery(includeNavigations, filters);
    
            return await query
                    // Use AsNoTracking to disable EF change tracking
                    // Use ToListAsync to avoid blocking a thread
                    .AsNoTracking().FirstOrDefaultAsync();
        }
    
        public async Task<SemesterDto> GetSemesterAsync(int id, String[] includeNavigations, params Expression<Func<Semester, bool>>[] filters)
        {
            // Get Semester  
            IQueryable<SemesterDto> query = SemesterQuery(includeNavigations, filters);
    
            return await query
                    // Use AsNoTracking to disable EF change tracking
                    // Use ToListAsync to avoid blocking a thread
                    .AsNoTracking().SingleOrDefaultAsync(m => m.Id == id);
        }
        // -EntityQuery
    
        // +DtoQuery
        public static IQueryable<SemesterDto> DtoQuery(AppDbContext context, string[] includeNavigations, params Expression<Func<SemesterDto, bool>>[] filters)
        {
            var query = context.Semesters.AsQueryable();
    
            if (includeNavigations != null && includeNavigations.Count() > 0)
            {
                // include navigation entity
                foreach (var navigation in includeNavigations)
                {
                    query = query.Include(navigation);
                }
            }
    
            var query2 = query.Select(SemesterDto.AsSemesterDto);
    
            if (filters != null && filters.Count() > 0)
            {
                // filter entity
                foreach (var filter in filters)
                {
                    query2 = query2.Where(filter);
                }
            }
    
            return query2;
        }
    
        protected IQueryable<SemesterDto> SemesterDtoQuery(String[] includeNavigations, params Expression<Func<SemesterDto, bool>>[] filters)
        {
            var query = DtoQuery(_context, includeNavigations, filters);
    
            return query;
        }        
    
        public async Task<List<SemesterDto>> GetSemesterDtoesAsync(String[] includeNavigations, params Expression<Func<SemesterDto, bool>>[] filters)
        {
    
            IQueryable<SemesterDto> query = SemesterDtoQuery(includeNavigations, filters);
    
            return await query
                        // Use AsNoTracking to disable EF change tracking
                        // Use ToListAsync to avoid blocking a thread
                        .AsNoTracking().ToListAsync();
        }
    
        public async Task<SemesterDto> GetSemesterDtoAsync(String[] includeNavigations, params Expression<Func<SemesterDto, bool>>[] filters)
        {
            // Get Semester  
            IQueryable<SemesterDto> query = SemesterDtoQuery(includeNavigations, filters);
    
            return await query
                    // Use AsNoTracking to disable EF change tracking
                    // Use ToListAsync to avoid blocking a thread
                    .AsNoTracking().FirstOrDefaultAsync();
        }
    
        public async Task<SemesterDto> GetSemesterDtoAsync(int id, String[] includeNavigations, params Expression<Func<SemesterDto, bool>>[] filters)
        {
            // Get Semester  
            IQueryable<SemesterDto> query = SemesterDtoQuery(includeNavigations, filters);
    
            return await query
                    // Use AsNoTracking to disable EF change tracking
                    // Use ToListAsync to avoid blocking a thread
                    .AsNoTracking().SingleOrDefaultAsync(m => m.Id == id);
        }
        // -DtoQuery
    
        public async Task<SemesterDto> CreateSemesterAsync(SemesterDto semesterDto, string username)
        {
    
            if (_context.Semesters.Any(a => a.Name == semesterDto.Name) == true)
            {
                throw new Exception("Record exist and caused a conflict!");
            }
    
            OnCreate(semesterDto, username);
    
            var entity = SemesterDto.AsSemesterFunc(semesterDto);
            
            ToEntity(ref entity, semesterDto);
            //entity.InsertUser = entity.LastActivityUser = username;
            //entity.InsertDateTime = entity.LastActivityDateTime = DateTime.UtcNow;
            entity.AddTracker(username);
    
            _context.Semesters.Add(entity);
    
            OnBeforeCreate(entity, username);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch(Exception ex)
            {
                // _context.Entry(entity).State = EntityState.Detached;
                throw new Exception("Add error", ex);
            }
            finally
            {
                // _context.Entry(entity).State = EntityState.Detached;
            }
            OnAfterCreate(entity, username);
    
            // semesterDto = SemesterDto.AsSemesterDtoFunc(entity);
            semesterDto = await GetSemesterDtoAsync(entity.Id, SemesterDto.IncludeNavigations());
        
            return semesterDto;
        }
        partial void OnCreate(SemesterDto semesterDto, string username);
        partial void OnBeforeCreate(Semester entity, string username);
        partial void OnAfterCreate(Semester entity, string username);
    
        public async Task<bool> UpdateSemesterAsync(SemesterDto semesterDto, string username/*, String[] includeNavigations, params Expression<Func<Semester, bool>>[] filters*/)
        {
            OnUpdate(semesterDto, username);
            
            // Get Semester  
            var entity = EntityQuery(_context, SemesterDto.IncludeNavigations())
                                    .FirstOrDefault(x => x.Id == semesterDto.Id);
    
            if (entity != null)
            {
                entity = SemesterDto.ToSemesterFunc(entity, semesterDto);
    
                ToEntity(ref entity, semesterDto);
                //entity.UpdateUser = entity.LastActivityUser = username;
                //entity.UpdateDateTime = entity.LastActivityDateTime = DateTime.UtcNow;
                entity.EditTracker(username);
    
                OnBeforeUpdate(entity, username);
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch(Exception ex)
                {
                    // _context.Entry(entity).State = EntityState.Detached;
                    throw new Exception("Update error", ex);
                }
                finally
                {
                    // _context.Entry(entity).State = EntityState.Detached;
                }
                OnAfterUpdate(entity, username);        
            }
            else
            {
                return false;
            }
    
            return true;
        }
        partial void OnUpdate(SemesterDto semesterDto, string username);
        partial void OnBeforeUpdate(Semester entity, string username);
        partial void OnAfterUpdate(Semester entity, string username);
    
        public async Task<bool> DeleteSemesterAsync(SemesterDto semesterDto)
        {
            OnDelete(semesterDto);
    
            var entity = _context.Semesters
                                .Where(x => x.Id == semesterDto.Id)
                                .FirstOrDefault();
    
            if (entity != null)
            {
                _context.Semesters.Remove(entity);
    
                OnBeforeDelete(entity);
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateException ex)
                {
                    // _context.Entry(entity).State = EntityState.Detached;
    
                    var sqlException = ex.GetBaseException() as SqlException;
    
                    if (sqlException != null)
                    {
                        var errorMessage = "deleting error";
    
                        var number = sqlException.Number;
        
                        if (number == 547)
                        {
                            string table = GetErrorTable(sqlException) ?? "descendant";
                            errorMessage = $"Must delete {table} records before deleting Semester";
                        }
    
                        throw new Exception(errorMessage, ex);
                    }
                }
                finally
                {
                    // _context.Entry(entity).State = EntityState.Detached;
                }
                OnAfterDelete(entity);    
            }
            else
            {
                return false;
            }
    
            return true;
        }
        partial void OnDelete(SemesterDto semesterDto);
        partial void OnBeforeDelete(Semester entity);
        partial void OnAfterDelete(Semester entity);
    
        public async Task<List<SemesterCache>> GetSemesterCachesAsync()
        {
            var list = await _context.Semesters.Select(SemesterCache.AsSemesterCache)
                        
                        // Use AsNoTracking to disable EF change tracking
                        // Use ToListAsync to avoid blocking a thread
                        .AsNoTracking().ToListAsync();
            return list.OrderBy(o => o.Name).ToList();
        }
    
        partial void ToEntity(ref Semester entity, SemesterDto semesterDto);    
    }
}
