//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.ResultCheckers.Dtos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using System.Linq.Expressions;
    using Ark.ResultCheckers.Entities;
    
    public partial class SessionDto : BaseNameEntityDto
    {
        public SessionDto()
        {
    		
            OnInitialize();
        }
    
        partial void OnInitialize();
    
    	private static Expression<Func<Session, SessionDto>> _asSessionDto;
        public static Expression<Func<Session, SessionDto>> AsSessionDto
        {
            get
            {
                SetConverters();
                return _asSessionDto;
            }
        }
        
        private static Func<Session, SessionDto> _asSessionDtoFunc;
        public static Func<Session, SessionDto> AsSessionDtoFunc
        {
            get
            {
                SetConverters();
                return _asSessionDtoFunc;
            }
        }
        
        private static Expression<Func<SessionDto, Session>> _asSession;
        public static Expression<Func<SessionDto, Session>> AsSession
        {
            get
            {
                SetConverters();
                return _asSession;
            }
        }
        
        private static Func<SessionDto, Session> _asSessionFunc;
        public static Func<SessionDto, Session> AsSessionFunc
        {
            get
            {
                SetConverters();
                return _asSessionFunc;
            }
        }
    
    	private static Func<Session, SessionDto, Session> _toSessionFunc;
        public static Func<Session, SessionDto, Session> ToSessionFunc
        {
            get
            {
                SetConverters();
                return _toSessionFunc;
            }
        }
    
    	/*
    	private static Expression<Func<Session, string>> _orderSession;
        public static Expression<Func<Session, string>> OrderSession
        {
            get
            {
                SetConverters();
                return _orderSession;
            }
        }
    	*/
    
    	private static Expression<Func<Session, bool>> SearchExpression(string searchString)
        {
            return 
    				w => w.Id.ToString().Contains(searchString) 
    			|| w.Name.Contains(searchString) 
    			;
        }
    
        static IQueryable<Session> _searchQuery;
        public static IQueryable<Session> Search(IQueryable<Session> query, string searchString)
        {
            _searchQuery = query.Where(
    						SearchExpression(searchString)
    					);
    		OnSetSearchQuery(query, searchString);
    		return _searchQuery;
    	}
    
        static IOrderedQueryable<Session> _orderQuery;
        public static IOrderedQueryable<Session> OrderBy(IQueryable<Session> query)
        {
    		_orderQuery = query.OrderBy(o => o.Name);
    		OnSetOrderQuery(query);
            return _orderQuery;
        }
    
        static IOrderedQueryable<SessionDto> _orderQueryDto;
        public static IOrderedQueryable<SessionDto> OrderBy(IQueryable<SessionDto> query)
        {
    		_orderQueryDto = query.OrderBy(o => o.Name);
            OnSetOrderQuery(query);
            return _orderQueryDto;
        }
    
    	static string[] _includeNavigations;
        public static string[] IncludeNavigations()
        {
            _includeNavigations = new string[] { 
    		};
            OnSetIncludeNavigations();
            return _includeNavigations;
        }
    
        static Expression<Func<Session, bool>>[] _filters;
        public static Expression<Func<Session, bool>>[] Filters(string searchString)
        {
            _filters = new Expression<Func<Session, bool>>[]
    					   {
    							SearchExpression(searchString)
    
    					   };
            OnSetFilters(searchString);
            return _filters;
        }
    
    
    	private static void SetConverters()
        {
            _asSessionDto = x => new SessionDto
            {
                
                Id = x.Id,
                
                Name = x.Name,
                // DisplayName = x.DisplayName,
                // Description = x.Description,
                
                IsVisible = x.IsVisible,
                InsertUser = x.InsertUser,
                InsertDateTime = x.InsertDateTime,
                UpdateUser = x.UpdateUser,
                UpdateDateTime = x.UpdateDateTime,
                LastActivityUser = x.LastActivityUser,
                LastActivityDateTime = x.LastActivityDateTime,
                Version = x.Version
            };
    
            _asSession = x => new Session
            {
                
                Id = x.Id,
                
                Name = x.Name,
                // DisplayName = x.DisplayName,
                // Description = x.Description,
                
                IsVisible = x.IsVisible,
                InsertUser = x.InsertUser,
                InsertDateTime = x.InsertDateTime,
                UpdateUser = x.UpdateUser,
                UpdateDateTime = x.UpdateDateTime,
                LastActivityUser = x.LastActivityUser,
                LastActivityDateTime = x.LastActivityDateTime,
                Version = x.Version
                 
            };
    
            _toSessionFunc = (y,x) => {
                
                y.Id = x.Id;
                
                y.Name = x.Name;
                // y.DisplayName = x.DisplayName;
                
                y.IsVisible = x.IsVisible;
                y.InsertUser = x.InsertUser;
                y.InsertDateTime = x.InsertDateTime;
                y.UpdateUser = x.UpdateUser;
                y.UpdateDateTime = x.UpdateDateTime;
                y.LastActivityUser = x.LastActivityUser;
                y.LastActivityDateTime = x.LastActivityDateTime;
                // y.Version = x.Version;
          
    			return y;
            };
    
            OnSetConverters();
    
            _asSessionFunc = _asSession.Compile();
            _asSessionDtoFunc = _asSessionDto.Compile();
        }
    
        static partial void OnSetConverters();
        static partial void OnSetOrderQuery(IQueryable<Session> query);
        static partial void OnSetOrderQuery(IQueryable<SessionDto> query);
        static partial void OnSetSearchQuery(IQueryable<Session> query, string searchString);
        static partial void OnSetOrders();
        static partial void OnSetIncludeNavigations();
        static partial void OnSetFilters(string searchString);
    }
}
