//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.ResultCheckers.Dtos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using System.Linq.Expressions;
    using Ark.ResultCheckers.Entities;
    
    public partial class CardDto : BaseEntityDto
    {
        public CardDto()
        {
    		
            OnInitialize();
        }
    
        partial void OnInitialize();
    
        [Required(ErrorMessage = "The Pin is a mandatory Field.")]
    	[Display(Name = "Pin")]
    	public string Pin { get; set; }
    	private static Expression<Func<Card, CardDto>> _asCardDto;
        public static Expression<Func<Card, CardDto>> AsCardDto
        {
            get
            {
                SetConverters();
                return _asCardDto;
            }
        }
        
        private static Func<Card, CardDto> _asCardDtoFunc;
        public static Func<Card, CardDto> AsCardDtoFunc
        {
            get
            {
                SetConverters();
                return _asCardDtoFunc;
            }
        }
        
        private static Expression<Func<CardDto, Card>> _asCard;
        public static Expression<Func<CardDto, Card>> AsCard
        {
            get
            {
                SetConverters();
                return _asCard;
            }
        }
        
        private static Func<CardDto, Card> _asCardFunc;
        public static Func<CardDto, Card> AsCardFunc
        {
            get
            {
                SetConverters();
                return _asCardFunc;
            }
        }
    
    	private static Func<Card, CardDto, Card> _toCardFunc;
        public static Func<Card, CardDto, Card> ToCardFunc
        {
            get
            {
                SetConverters();
                return _toCardFunc;
            }
        }
    
    	/*
    	private static Expression<Func<Card, string>> _orderCard;
        public static Expression<Func<Card, string>> OrderCard
        {
            get
            {
                SetConverters();
                return _orderCard;
            }
        }
    	*/
    
    	private static Expression<Func<Card, bool>> SearchExpression(string searchString)
        {
            return 
    				w => w.Id.ToString().Contains(searchString) 
    			|| w.Pin.Contains(searchString) //@string
    			;
        }
    
        static IQueryable<Card> _searchQuery;
        public static IQueryable<Card> Search(IQueryable<Card> query, string searchString)
        {
            _searchQuery = query.Where(
    						SearchExpression(searchString)
    					);
    		OnSetSearchQuery(query, searchString);
    		return _searchQuery;
    	}
    
        static IOrderedQueryable<Card> _orderQuery;
        public static IOrderedQueryable<Card> OrderBy(IQueryable<Card> query)
        {
    		_orderQuery = query.OrderBy(o => o.Id);
    		OnSetOrderQuery(query);
            return _orderQuery;
        }
    
        static IOrderedQueryable<CardDto> _orderQueryDto;
        public static IOrderedQueryable<CardDto> OrderBy(IQueryable<CardDto> query)
        {
    		_orderQueryDto = query.OrderBy(o => o.Id);
            OnSetOrderQuery(query);
            return _orderQueryDto;
        }
    
    	static string[] _includeNavigations;
        public static string[] IncludeNavigations()
        {
            _includeNavigations = new string[] { 
    		};
            OnSetIncludeNavigations();
            return _includeNavigations;
        }
    
        static Expression<Func<Card, bool>>[] _filters;
        public static Expression<Func<Card, bool>>[] Filters(string searchString)
        {
            _filters = new Expression<Func<Card, bool>>[]
    					   {
    							SearchExpression(searchString)
    
    					   };
            OnSetFilters(searchString);
            return _filters;
        }
    
    
    	private static void SetConverters()
        {
            _asCardDto = x => new CardDto
            {
                
                Id = x.Id,
    			// +simplex
    			Pin = x.Pin,
                
                IsVisible = x.IsVisible,
                InsertUser = x.InsertUser,
                InsertDateTime = x.InsertDateTime,
                UpdateUser = x.UpdateUser,
                UpdateDateTime = x.UpdateDateTime,
                LastActivityUser = x.LastActivityUser,
                LastActivityDateTime = x.LastActivityDateTime,
                Version = x.Version
            };
    
            _asCard = x => new Card
            {
                
                Id = x.Id,
    			// +simple
    			Pin = x.Pin,
                
                IsVisible = x.IsVisible,
                InsertUser = x.InsertUser,
                InsertDateTime = x.InsertDateTime,
                UpdateUser = x.UpdateUser,
                UpdateDateTime = x.UpdateDateTime,
                LastActivityUser = x.LastActivityUser,
                LastActivityDateTime = x.LastActivityDateTime,
                Version = x.Version
                 
            };
    
            _toCardFunc = (y,x) => {
                
                y.Id = x.Id;
    			// +simple
    			y.Pin = x.Pin;
                
                y.IsVisible = x.IsVisible;
                y.InsertUser = x.InsertUser;
                y.InsertDateTime = x.InsertDateTime;
                y.UpdateUser = x.UpdateUser;
                y.UpdateDateTime = x.UpdateDateTime;
                y.LastActivityUser = x.LastActivityUser;
                y.LastActivityDateTime = x.LastActivityDateTime;
                // y.Version = x.Version;
          
    			return y;
            };
    
            OnSetConverters();
    
            _asCardFunc = _asCard.Compile();
            _asCardDtoFunc = _asCardDto.Compile();
        }
    
        static partial void OnSetConverters();
        static partial void OnSetOrderQuery(IQueryable<Card> query);
        static partial void OnSetOrderQuery(IQueryable<CardDto> query);
        static partial void OnSetSearchQuery(IQueryable<Card> query, string searchString);
        static partial void OnSetOrders();
        static partial void OnSetIncludeNavigations();
        static partial void OnSetFilters(string searchString);
    }
}
