//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code.Entities
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using Microsoft.EntityFrameworkCore;
    
    public enum MediaType : int
    {
        Text = 0,
        Image = 1,
        Video = 2,
        Audio = 3,
        Application = 4,
        Pdf = 5,
        Csv = 6,
        Zoom = 7
    }
}
