//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.ResultCheckers.Dtos.Caches
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq.Expressions;
    using Ark.ResultCheckers.Entities;
    
    public partial class CourseCache : BaseEntityCache
    {
        public CourseCache()
        {
            OnInitialize();
        }
    
        partial void OnInitialize();
    
    
        private static Expression<Func<Course, string>> _orderCourse;
        public static Expression<Func<Course, string>> OrderCourse
        {
            get
            {
                SetConverters();
                return _orderCourse;
            }
        }
        
    	private static Expression<Func<Course, CourseCache>> _asCourseCache;
        public static Expression<Func<Course, CourseCache>> AsCourseCache
        {
            get
            {
                SetConverters();
                return _asCourseCache;
            }
        }
        
        private static Func<Course, CourseCache> _asCourseCacheFunc;
        public static Func<Course, CourseCache> AsCourseCacheFunc
        {
            get
            {
                SetConverters();
                return _asCourseCacheFunc;
            }
        }
        
    	private static void SetConverters()
        {
            _orderCourse = x => x.Id.ToString();
    
            _asCourseCache = x => new CourseCache
            {
    			Id = x.Id,
                
                Name = x.CourseName,
    			
            };
    
            OnSetConverters();
    
            _asCourseCacheFunc = _asCourseCache.Compile();
        }
    
        static partial void OnSetConverters();
    
    
    	
    }
}
