//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.ResultCheckers.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using Microsoft.EntityFrameworkCore;
    
    public partial class BulkCard : BulkEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BulkCard()
        {
            this.Role = "\"Users\"";
    		Initialize();
        }
    	partial void Initialize();
    
        [Required(ErrorMessage = "The Pin is a mandatory Field.")]
    	[Display(Name = "Pin")]
    	public string Pin { get; set; }
        [Display(Name = "Owner")]
    	public string Owner { get; set; }
        [Required(ErrorMessage = "The Role is a mandatory Field.")]
    	[Display(Name = "Role")]
    	public string Role { get; set; }
        [Required(ErrorMessage = "The Username is a mandatory Field.")]
    	[Display(Name = "Username")]
    	public string Username { get; set; }
    }
}
