//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.ResultCheckers.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using Microsoft.EntityFrameworkCore;
    
    public partial class Grade : BaseNameEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grade()
        {
    		Initialize();
        }
    	partial void Initialize();
    
        [Display(Name = "Begin Mark")]
    	public double BeginMark { get; set; }
        [Display(Name = "Next Begin Mark")]
    	public double NextBeginMark { get; set; }
        [Display(Name = "Point")]
    	public double Point { get; set; }
    }
}
